config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :themes
  # Create routes for /:id for users, but constrain the routes to not be in the list of reserved words
  # (e.g. admin, analytics, appearance, settings, up, etc.)
  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end
  # link_position_path update
  patch '/link_position/:id', to: 'links#update_position', as: :link_position

  devise_for :users
  root 'admin#index'
  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update
  # Update theme for profile pages on appearance page
  patch 'admin/update_theme', to: 'admin#update_theme', as: :admin_update_theme

  get 'admin/manage_socials', to: 'admin#manage_socials', as: :admin_manage_socials
  patch 'admin/update_socials', to: 'admin#update_socials', as: :admin_update_socials

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/theme.rb
# frozen_string_literal: true

class Theme < ApplicationRecord
  # Hey Future Dean,
  # Theme types are used to determine between profile or admin dashboard themes probably.

  # def users_with_this_as_profile_theme
  #   User.where(profile_theme_id: id)
  # end

  # def users_with_this_as_admin_theme
  #   User.where(admin_theme_id: id)
  # end

  def self.default_css_value
    '--light-theme'
  end

  def self.default_theme
    find_by(css_value: default_css_value)
  end
end

app/controllers/themes_controller.rb
# frozen_string_literal: true

class ThemesController < ApplicationController
  before_action :set_theme, only: %i[show edit update destroy]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show; end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit; end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy!

    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_theme
    @theme = Theme.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def theme_params
    params.require(:theme).permit(:name, :theme_type, :premium, :css_value)
  end
end

app/helpers/themes_helper.rb
# frozen_string_literal: true

module ThemesHelper
end

app/views/themes/_form.html.erb
<%= simple_form_for(@theme) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :theme_type %>
    <%= f.input :premium %>
    <%= f.input :css_value %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/themes/_profile_theme_selector.html.erb
<%= simple_form_for(current_user, url: admin_update_theme_url) do |f| %>
  <!-- Dropdown select theme by name but send id of theme back to server. -->
  <%= f.input :profile_theme_id, 
              collection: Theme.all.uniq, 
              label_method: :name, 
              value_method: :id,
              include_blank: false, 
              label: false %>
  <div class="form-actions">
    <%= f.button :submit, "Update Theme", class: "btn btn-primary devise-card-button" %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <p>
    <strong>Name:</strong>
    <%= theme.name %>
  </p>

  <p>
    <strong>Theme type:</strong>
    <%= theme.theme_type %>
  </p>

  <p>
    <strong>Premium:</strong>
    <%= theme.premium %>
  </p>

  <p>
    <strong>Css value:</strong>
    <%= theme.css_value %>
  </p>

</div>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Themes</h1>

<div id="themes">
  <% @themes.each do |theme| %>
    <%= render theme %>
    <p>
      <%= link_to "Show this theme", theme %>
    </p>
  <% end %>
</div>

<%= link_to "New theme", new_theme_path %>

app/views/themes/new.html.erb
<div class="container mt-5">
  <h1>New theme</h1>
  <%= render "form", theme: @theme %>
  <br>
  <div>
    <%= link_to "Back to themes", themes_path %>
  </div>
</div>

app/views/themes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @theme %>

<div>
  <%= link_to "Edit this theme", edit_theme_path(@theme) %> |
  <%= link_to "Back to themes", themes_path %>

  <%= button_to "Destroy this theme", @theme, method: :delete %>
</div>