config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :themes
  # Create routes for /:id for users, but constrain the routes to not be in the list of reserved words
  # (e.g. admin, analytics, appearance, settings, up, etc.)
  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end
  # link_position_path update
  patch '/link_position/:id', to: 'links#update_position', as: :link_position

  devise_for :users
  root 'admin#index'
  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update
  # Update theme for profile pages on appearance page
  patch 'admin/update_theme', to: 'admin#update_theme', as: :admin_update_theme

  get 'admin/manage_socials', to: 'admin#manage_socials', as: :admin_manage_socials
  patch 'admin/update_socials', to: 'admin#update_socials', as: :admin_update_socials

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admin/_preview.html.erb
<%= turbo_frame_tag "preview" do %>
  <iframe src="<%= profile_url(current_user) %>" 
        class="phone-border"
        width="100%" 
        height="100%" 
        frameborder="0" 
        scrolling="yes"></iframe>
<% end %>

app/views/admin/analytics.html.erb
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<div class="container mt-5">
  <h1>Admin#analytics</h1>
  <%= mixed_charts({ theme: "palette2", yaxis: {min: 0, forceNiceScale: true}, stacked: true}) do %>
    <% column_chart(name: "Total Views", data: @daily_profile_views ) %>
    <% column_chart(name: "Link Clicks", data: @daily_link_clicks) %>
  <% end %>
  <h3>Device Views</h3>
  <!-- Remember to cover how to find the datalabels docs in the gem documentation,
  and then how you converted that to the legend configuration using the apex
  js library docs. -->
  <%= donut_chart(@daily_device_views_by_type, legend: {
  labels: {
    colors: '#FFF' # Or an array to individually style.
  }
}) %>
</div>

app/views/admin/appearance.html.erb
<div class="container">
  <h1>Profile</h1>
  <div class="row">
    <div class="col-8">
      <div class="mt-5 mb-5 devise-card">
        <%= simple_form_for(current_user, url: admin_update_path) do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :username, required: true, label: false, placeholder: "Username..." %>
            <%= f.input :avatar, required: false %>
            <%= f.input :name,
                required: true,
                label: false,
                placeholder: "Name...",
                input_html: { autocomplete: "name" } %>
            <%= f.input :bio,
                required: true,
                label: false,
                placeholder: "About you...",
                input_html: { autocomplete: "name" } %>
          </div>
          <div class="form-actions">
            <%= f.button :submit, "Update", class:"btn btn-primary devise-card-button" %>
          </div>
        <% end %>
      </div>
      <div class="mt-5 mb-5 devise-card">
        <h3>Theme(s)</h3>
        <%= render partial: "themes/profile_theme_selector" %>
      </div>
    </div>
    <div class="col-4">
      <%= render partial: "admin/preview" %>
    </div>
  </div>
  <div class="row mt-5">
  </div>
</div>

app/views/admin/index.html.erb
<div class="container">
  <div class="text-center m-5">
    <h1 class="text-center"><%= current_user.username %></h1>
    <%= render partial: "links/share_button", locals: { url: profile_url(current_user) } %>
  </div>
  <div class="text-center m-3">
    <%= render partial: "links/form", locals: { link: Link.new } %>
  </div>
  <hr />
  <div class="row">
    <div class="col-8">
      <div id="links" 
        data-controller="sortable" 
        data-sortable-resource-name-value="link"
        data-sortable-handle-value=".link_handle">
        <% @links.each do |link| %>
          <%= render partial: "links/admin_link", locals: { link: link } %>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <%= render partial: "admin/preview" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3>Social Links</h3>
      <%= link_to "Social Selector", admin_manage_socials_path %>
      <%= turbo_frame_tag "modal" do %>
        <% 10.times do %>
          <div class="row">
            <i class="bi bi-facebook"></i>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: "links/copy_toast" %>

app/views/admin/manage_socials.html.erb
<div class="container mt-5">
  <%= simple_form_for(current_user, url: admin_update_socials_path) do |f| %>
    <div class="row">
      <div class="col">
        <h3>Social Links</h3>
        <% 10.times do %>
          <div class="row mb-2">
            <div class="col">
              <div class="form-group">
                <i class="bi bi-facebook"></i>
                <input>
                Enabled?
                <input type="checkbox">
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/settings.html.erb
<h1>Admin#settings</h1>
<p>Find me in app/views/admin/settings.html.erb</p>