config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :themes
  # Create routes for /:id for users, but constrain the routes to not be in the list of reserved words
  # (e.g. admin, analytics, appearance, settings, up, etc.)
  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end
  # link_position_path update
  patch '/link_position/:id', to: 'links#update_position', as: :link_position

  devise_for :users
  root 'admin#index'
  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update
  # Update theme for profile pages on appearance page
  patch 'admin/update_theme', to: 'admin#update_theme', as: :admin_update_theme

  get 'admin/manage_socials', to: 'admin#manage_socials', as: :admin_manage_socials
  patch 'admin/update_socials', to: 'admin#update_socials', as: :admin_update_socials

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to "Linktree", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= active_link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Appearance", admin_appearance_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Analytics", admin_analytics_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Settings", admin_settings_path, class:"nav-link" %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username_before_type_cast %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "My Account", edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>