config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :themes
  # Create routes for /:id for users, but constrain the routes to not be in the list of reserved words
  # (e.g. admin, analytics, appearance, settings, up, etc.)
  get '/:slug', to: 'profiles#show', as: :user

  resources :links, only: %i[create update destroy] do
    patch 'toggle_active', on: :member
  end
  # link_position_path update
  patch '/link_position/:id', to: 'links#update_position', as: :link_position

  devise_for :users
  root 'admin#index'
  get 'admin/index'
  get 'admin/appearance'
  get 'admin/analytics'
  get 'admin/settings'
  patch 'admin/update', to: 'admin#update', as: :admin_update
  # Update theme for profile pages on appearance page
  patch 'admin/update_theme', to: 'admin#update_theme', as: :admin_update_theme

  get 'admin/manage_socials', to: 'admin#manage_socials', as: :admin_manage_socials
  patch 'admin/update_socials', to: 'admin#update_socials', as: :admin_update_socials

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :user
  acts_as_list
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, only: %i[update destroy update_position toggle_active]

  def create
    @link = current_user.links.build(link_params)

    if @link.save
      redirect_to admin_index_path, notice: 'Link was successfully created.'
    else
      redirect_to admin_index_path, notice: 'Link was not created.'
    end
  end

  def update
    if @link.update(link_params)
      redirect_to admin_index_path, notice: 'Link was successfully updated.'
    else
      redirect_to admin_index_path, notice: 'Link was not updated.'
    end
  end

  def destroy
    @link.destroy
    redirect_to admin_index_path, notice: 'Link was successfully destroyed.'
  end

  def update_position
    position = params.dig(:link, :position).to_i
    @link.insert_at(position)
  end

  def toggle_active
    active_value = params.dig(:link, :active)
    @link.update(active: active_value)
    request.format = :turbo_stream

    respond_to do |format|
      format.html
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('preview', partial: 'admin/preview')
      end
    end
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:name, :url, :active, :position)
  end
end

app/helpers/links_helper.rb
# frozen_string_literal: true

module LinksHelper
end

app/views/links/_admin_active_toggle.html.erb
<turbo-frame id="link_active_toggle_<%= link.id %>">
  <%= simple_form_for link, 
    url: toggle_active_link_path(link), format: :turbo_stream do |f| %>
    <%= f.input :active, 
        as: :boolean, 
        inline_label: false, 
        label: false,
        # This polyfill allows you to use the onchange event with a turbo_stream.
        # See: https://stackoverflow.com/questions/68624668/how-can-i-submit-a-form-on-input-change-with-turbo-streams
        input_html: { onchange: "this.form.requestSubmit();" } %>
  <% end %>
</turbo-frame>

app/views/links/_admin_link.html.erb
<div class="row link" data-sortable-update-url="<%= link_position_path(link) %>">
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><i class="bi bi-grip-vertical link_handle"></i><%= link.name %></h5>
        <div class="row">
          <div class="col-8 link-centered">
            <%= render partial: "links/inline_form", locals: { link: link } %>
          </div>
          <div class="col-4">
            <%= render "links/link_actions", link: link %>
          </div>
        </div>
        <div class="btn-group btn-group-sm mt-2" role="group" aria-label="...">
          <div>
            <%= link_to "Visit Link", 
            url_for(link.url), 
            class:"btn btn-primary borderless", 
            target: "_blank",
            rel: "noopener noreferrer" %>
          </div>
          <div>
            <%= button_to "Delete", link, class: "btn btn-danger borderless", method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-2"></div>
</div>

app/views/links/_copy_toast.html.erb
<div id="copy-toast" class="toast align-items-center text-white bg-success border-0 position-fixed bottom-0 end-0" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="d-flex">
    <div class="toast-body">
      Copied URL to clipboard!
    </div>
    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>

app/views/links/_form.html.erb
<%= form_with model: link, url: links_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/links/_inline_form.html.erb
<turbo-frame id="link_url_<%= link.id %>" data-controller="edit-link">
  <span class="link-text" 
                data-action="click->edit-link#showForm" 
    data-edit-link-target="content"><%= link.url %></span>
  <div class="edit-form d-none" data-edit-link-target="form">
    <%= simple_form_for link, 
                  url: link_path(link), 
                  data: { turbo: true } do |f| %>
      <%= f.input :url, label: false %>
      <%= link_to "Cancel", nil, data: {
                    edit_link_target: "Cancel", 
                    action: "click->edit-link#hideForm"},
                    class: "btn btn-secondary" %> <%= f.submit "Update", class:"btn btn-primary" %>
    <% end %>
  </div>
</turobo-frame>

app/views/links/_link.html.erb
<div class="row">
  <div class="col-lg-2 col-sm-0"></div>
  <div class="col-lg-8 col-sm-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link.name %></h5>
        <%= link_to link.url, 
          target: "_blank", 
          class: "linkable btn btn-secondary",
          data: { controller: "links", action: "click->links#click", link: link } do %>
          <%= link.url %>
        <% end %>
        <a href="<%= link.url %>" class="btn btn-primary">Go to link</a>
      </div>
    </div>
  </div>
  <div class="col-lg-2 col-sm-0"></div>
</div>

app/views/links/_link_actions.html.erb
<div class="row justify-content-end">
  <div class="col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-center">
    <%= render partial: "links/share_button", locals: { url: url_for(link.url) } %>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12 d-flex align-items-center">
    <div class="form-check form-switch custom-switch-center">
      <%= render partial: "links/admin_active_toggle", locals: { link: link } %>
    </div>
  </div>
</div>

app/views/links/_share_button.html.erb
<%= link_to url, 
    class: "btn btn-outline-secondary btn-sm", 
    data: { 
      controller: "clipboard-button",
      clipboard_button_url_value: url,
      action: "click->clipboard-button#copy"
    }, 
    role: "button" do %>
  <span class="d-none d-lg-inline">Share</span> <i class="bi bi-share"></i>
<% end %>